### ISSUE TITLE
Dynamic DNS Updates and TLS certs

### ISSUE THREAD

**Issue by chris-short** [libdns/netlify#1]
Hi all,

I recently tried to move a caddy site from Cloudflare DNS to Netlify's DNS. The Netlify Caddyfile configuration was something I simply could not figure out. I went to the [Netlify](https://answers.netlify.com/t/caddy-and-netlify-dns/74288/2?u=chrisshort) and [Caddy](https://caddy.community/t/caddy-and-netlify-dns/16974) forums for assistance. My issue was that Caddy couldn't get a TLS cert issued because I was "unauthorized" (error 401) to do anything against Netlify DNS.

But, now that I have a Dynamic DNS tool that appears to be working with the record needing updating, Caddy is able to issue TLS certificates and work as intended. I just wish it worked all natively in Caddy.

**Comment by mholt** [comment]
(was this resolved with your Caddyfile change, @chris-short ?)

**Comment by chris-short** [comment]
Yes thank you.
