### ISSUE TITLE
Netlify Dynamic DNS getting a 404?

### ISSUE THREAD

**Issue by chris-short** [libdns/netlify#2]
While trying to use [caddy-dynamicdns](https://github.com/mholt/caddy-dynamicdns) (which consumes libdns) to update a record at Netlify, I'm getting a baffling error: **404**

I created [a thread on the Caddy forums](https://caddy.community/t/dynamic-dns-getting-a-404/17018) and Matt Holt is thinking this might be the culprit might be here: <https://github.com/libdns/netlify/blob/656199e15ce1bd40918776a847bad6b38256badb/client.go#L42>

To be clear, other things are working as they should with Netlify, just this one change record ability is not. Let me know if you need additional information here (most of it is on the Caddy forum; happy to bring it here).

**Comment by CL0Pinette** [comment]
Oh no, I'm so sorry, I just saw your issue today... I will look into it asap

**Comment by CL0Pinette** [comment]
I think that the fix is ready, I will have to make some tests on it to be sure.

I will try to release the fix in 5-6 hours.

Once again, sorry for the delay....

**Comment by CL0Pinette** [comment]
I had some complication to make the fix work, but it is now ready.
I will push it soon, I just need to check the integration with Caddy as I had to change the version of go from `1.17` to `1.18` to comply with the updates of some dependencies.
